[pytest]
# 添加测试文件的匹配模式，默认是 test*.py 和 *_test.py
python_files = test_*.py 案例*.py
# 添加测试类的匹配模式，默认是以 `Test` 开头的类
python_classes = Test*
# 添加测试函数的匹配模式，默认是以 `test` 开头的函数
python_functions = test* hehe*


# 定义测试文件路径，pytest会从这里开始查找测试
testpaths = .

# 定义测试选项，-v 表示详细模式，-s 表示显示 print 输出
addopts = -vs
;
markers =
    sit
    maoyan
    uat